scripts/change_url
- *Add port variable for NGINX regen config*
=> add port variable for NGINX regen config

scripts/backup, scripts/restore
Seems to be the only missing part?!?
=> Bugfix #16 by including the public path to backup/restore

scripts/_common.sh
=> Missing python3-venv

README.md
- *Line break and set badge to SVG*
=> Set badge to svg

scripts/change_url
https://ci-apps.yunohost.org/ci/job/599
see also: https://github.com/YunoHost/package_linter/issues/90
=> Fix change_url syntax error, see:

README.md, scripts/restore
see: https://ci-apps.yunohost.org/ci/job/636
=> fix restore: create log path and file before chown call

conf/requirements.txt, manifest.json, poetry.lock, pyproject.toml, tests/test_django_project.py
see: https://github.com/YunoHost-Apps/django_ynh/issues/7
=> Bugfix "CSRF verification failed on POST requests"

README.md
=> Add line break

README.md
https://github.com/YunoHost-Apps/pyinventory_ynh/issues/53 works out of the box ;)
=> Add info about emails into README

scripts/install, scripts/restore, scripts/upgrade
see: https://ci-apps-dev.yunohost.org/ci/job/4281
=> Fix file permissions

scripts/_common.sh, scripts/change_url, scripts/install, scripts/restore, scripts/upgrade
=> Bugfix CI run

manifest.json, pyproject.toml, scripts/_common.sh, scripts/change_url, scripts/install, scripts/restore, scripts/upgrade
Reverts YunoHost-Apps/pyinventory_ynh#90
=> Revert "Bugfix CI run" and fix it in a other way

.github/workflows/pytest.yml
=> uses: codecov/codecov-action@v2

conf/requirements.txt, manifest.json, poetry.lock, pyproject.toml
=> Update to PyInventory v0.14.0 and remove redundant dependencies

scripts/install, scripts/upgrade
=> Fix broken "manage.py"

README.md, README_fr.md, conf/requirements.txt, manifest.json, poetry.lock, pyproject.toml
=> Update to v0.16.0

scripts/change_url
=> Bugfix "change_url"

Makefile, poetry.lock
See also https://forum.yunohost.org/t/invalid-pep-440-version-0-16-0-ynh1/21293
=> "poetry<1.2" because of https://github.com/python-poetry/poetry/issues/6013

Makefile, README.md, README_fr.md, conf/requirements.txt, manifest.json, poetry.lock, pyproject.toml, tests/test_project_setup.py
=> master <- testing

.github/workflows/package_linter.yml, .github/workflows/pytest.yml, .gitignore, README.md, README_fr.md, conf/requirements.txt, conf/settings.py, manifest.json, poetry.lock, pyproject.toml, scripts/_common.sh, tests/test_django_project.py, tests/test_django_project_create_unknown_user_1.snapshot.html, tests/test_project_setup.py
Apply project updates from:
* https://github.com/jedie/cookiecutter_templates/tree/main/yunohost_django_package
and update requirements
=> Update to PyInventory v0.19.1

README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_zh_Hans.md, manifest.toml
=> Testing: explicit dependency to redis-server

README.md, README_es.md, README_eu.md, README_fr.md, README_gl.md, README_id.md, README_ru.md, README_zh_Hans.md, conf/requirements.txt, conf/urls.py, manifest.toml, pyinventory_ynh/__init__.py, pyproject.toml, requirements.dev.txt
=> Update to PyInventory v0.20.1

scripts/upgrade
For Yunohost v12 a change in nginx.conf is needed, that adds `proxy_set_header Ynh-User $http_ynh_user;`
But on an upgrade, the changes of nginx was not appied !
=> Bugfix update and missing nginx.conf changes
